### ISSUE TITLE
Netlify Demo Best Practices score 94

### ISSUE THREAD

**Issue by tempral** [google/eleventy-high-performance-blog#94] opened 2021-08-12 23:43 UTC
User Experience:
Fonts with `font-display: optional` are not preloaded

**Comment by cramforce** [comment] 2021-08-13 07:39
Yeah, I have a "fix" for this on my personal blog copy. It is quite complicated and I wonder whether it is worth porting when this is working as intended from a performance perspective.

**Comment by ZoltanVeres** [comment] 2021-09-07 14:37
@cramforce Can you point us to the right direction here? I mean a Draft PR would be ideal, even if it doesn't get merged, we could have some discussions around it, but short explanation might be enough.
I see that the `font-display: optional` gets added to the css on the build step, and after checking the [link on lighthouse](https://web.dev/preload-optional-fonts/?utm_source=lighthouse&utm_medium=devtools) i concluded that what really missing is `<link rel="preload">`, but this not applies in this case, since the css gets embedded into the html. So is this an issue on Lighthouse or should we need to fix it on our own?

**Comment by cramforce** [comment] 2021-09-07 21:55
I should really port my solution over. The easy "fix" is, indeed, to just add the link rel preload calls. This adds a FCP delay to Chrome which is why I try to not do it. Unfortunately, that is difficult to do in a way that makes Lighthouse happy.

It is definitely very reasonable to just adds the preloads and maybe that would be a good option for this repo.

**Closed** 2021-09-11 18:00 UTC
