### ISSUE TITLE
Unable to serve the files , see attached screenshot

### ISSUE THREAD

**Issue by lessgochamp** [google/eleventy-high-performance-blog#56] opened 2020-11-30 08:27 UTC
How do I run and see the blog on local. I m afraid to say that the read me steps are not helping me and getting blocked by several errors despite installing all npm modules:

![image](https://user-images.githubusercontent.com/75239793/100585504-b50f3500-3313-11eb-8554-ef76b106b97d.png)

On build command:
![image](https://user-images.githubusercontent.com/75239793/100585653-ebe54b00-3313-11eb-8c38-0f50bb246cb9.png)

I have installed `sharp` using npm install sharp

![image](https://user-images.githubusercontent.com/75239793/100585274-50ec7100-3313-11eb-8892-49fef27bab83.png)

Am I missing something here??
I m new to 11ty and have never used this before. Please help.

**Comment by 0501814314** [comment] 2020-12-25 23:57
إبن الحمدي

**Comment by hhh968574** [comment] 2020-12-26 00:22
الغاء

احصل على Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by nph278** [comment] 2021-02-18 01:27
There are a few issues on [sharp](https://github.com/lovell/sharp) about this. The most recent one (closed) is [here.](https://github.com/lovell/sharp/issues/2517). I can't get this to work at all.

**Comment by ZoltanVeres** [comment] 2021-09-09 14:56
Looking back to this issue, i think the problem is that the OP uses a node version older then 14.
In the repository there is an `.nvmrc` file which contains the node version the project suppose to run.
It is recommended to have `nvm` installed, because that let's you install different node versions and it also picks up the node version from the `.nvmrc` file. 

I think we should close this issue.

**Closed** 2021-09-09 16:14 UTC
